package SwingElements;

import java.awt.Color;

/**
 * Simple {@link JFrame} extension, used to display the average color of all
 * lines on the grid.
 */
public class AverageColorDisplay extends javax.swing.JFrame implements Runnable {

    /**
     * Constructor.
     */
    public AverageColorDisplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ColorDisplay = new javax.swing.JPanel();

        javax.swing.GroupLayout ColorDisplayLayout = new javax.swing.GroupLayout(ColorDisplay);
        ColorDisplay.setLayout(ColorDisplayLayout);
        ColorDisplayLayout.setHorizontalGroup(
            ColorDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        ColorDisplayLayout.setVerticalGroup(
            ColorDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ColorDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ColorDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ColorDisplay;
    // End of variables declaration//GEN-END:variables

    /**
     * Updates the color displayed.
     * 
     * @param in The new color to display
     */
    public void updateColor(Color in) {
        ColorDisplay.setBackground(in);
        ColorDisplay.repaint();
    }//end updateColor

    /**
     * Runner.
     */
    @Override
    public void run() {
        setVisible(true);
    }//end run
}//end AverageColorDisplay
