package SwingElements;

import graphvisualizer.GraphTuple;
import graphvisualizer.GraphTupleInfo;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 * Form used to input settings for a new line to be created.
 */
public class CustomLineForm extends javax.swing.JFrame implements Runnable {

    private GraphTupleInfo store;                               //The GraphTupleInfo object used to describe the line being created
    private boolean complete = true;                            //Boolean, checking to see if all input has been correctly entered after validation
    private Base ref;                                           //Base object, used to access other objects as needed
    private LineEventDetailsInputForm parent;                   //If set, the LineEventDetailsInputForm asking for a GraphTupleInfo object describing the line to be created

    /**
     * Constructor. Used when the user describes a line to be created by the
     * user.
     *
     * @param simIn The {@link Base} object used to access other objects as
     * needed
     */
    public CustomLineForm(Base simIn) {
        ref = simIn;
        parent = null;
        store = ref.getCanvas().getGtiStorage();
        this.setTitle("Custom Line Form");
        //initComponents();
    }//end constructor

    /**
     * Constructor. Used when the user describes a line to be created by a
     * {@link EventScheduler.Events.PlaceLineEvent}.
     *
     * @param in The {@link LineEventDetailsInputForm} asking for user input
     */
    CustomLineForm(LineEventDetailsInputForm in) {
        parent = in;
        ref = null;
        store = parent.gti;
    }//end constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        SubmitButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        EdgeCheckBox = new javax.swing.JCheckBox();
        EdgeLabel = new javax.swing.JLabel();
        CycleBaseCheckBox = new javax.swing.JCheckBox();
        CycleBaseLable = new javax.swing.JLabel();
        ReproductionClockTextField = new javax.swing.JTextField();
        ReproductionClockLabel = new javax.swing.JLabel();
        MutationTextField = new javax.swing.JTextField();
        MutationLabel = new javax.swing.JLabel();
        HealthTextField = new javax.swing.JTextField();
        HealthLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        SubmitButton.setText("OK");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed();
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(200, 400));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Line History");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        EdgeLabel.setText("Edge? ");

        CycleBaseLable.setText("Cycle Base?");

        ReproductionClockLabel.setText("Turns for reproduction: ");

        MutationLabel.setText("Mutation Chance(out of " + GraphTuple.MUTATION_DIVISOR + "):");

        HealthLabel.setText("Health: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HealthLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HealthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MutationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MutationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReproductionClockLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReproductionClockTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CycleBaseLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CycleBaseCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EdgeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EdgeCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EdgeCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CycleBaseCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(EdgeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(CycleBaseLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ReproductionClockTextField)
                .addComponent(ReproductionClockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(MutationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(MutationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(HealthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(HealthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(SubmitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SubmitButton))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Action method for the submit button. Validates input, enters it into a
     * {@link GraphTupleInfo} object, to be used when a line is created.
     */
    private void SubmitButtonActionPerformed() {//GEN-FIRST:event_SubmitButtonActionPerformed
        complete = true;
        store.startHealth = checkTextField(HealthTextField, "Starting Health");
        store.mutationPercentage = checkTextField(MutationTextField, "Mutation Percentage");
        store.reproductionClock = checkTextField(ReproductionClockTextField, "Reproduction Clock");
        store.color = jColorChooser1.getColor();
        store.cycleBase = CycleBaseCheckBox.isSelected();
        if (CycleBaseCheckBox.isSelected()) {
            if (store.startHealth > 0) {
                ref.getGraph().setCycleBase(store.startHealth);
            }//end if
        }//end if
        store.edge = EdgeCheckBox.isSelected();
        if (complete) {
            if (ref != null && parent == null) {
                ref.getCanvas().setGtiStorage(store);
            }//end if
            else if (parent != null && ref == null) {
                parent.gti = store;
            }//end else if
            this.dispose();
        }//end if
    }//GEN-LAST:event_SubmitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CycleBaseCheckBox;
    private javax.swing.JLabel CycleBaseLable;
    private javax.swing.JCheckBox EdgeCheckBox;
    private javax.swing.JLabel EdgeLabel;
    private javax.swing.JLabel HealthLabel;
    private javax.swing.JTextField HealthTextField;
    private javax.swing.JLabel MutationLabel;
    private javax.swing.JTextField MutationTextField;
    private javax.swing.JLabel ReproductionClockLabel;
    private javax.swing.JTextField ReproductionClockTextField;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    /**
     * Checks a given {@link JTextField} to ensure that the input is numerical
     * and greater than 0.
     *
     * @param field The {@link JTextField} to be checked.
     * @param title The title for the error message, should it be generated.
     * @return The final integer value after checking is performed
     */
    private int checkTextField(JTextField field, String title) {
        int out;
        try {
            out = Integer.parseInt(field.getText());
            if (out < 0) {
                JOptionPane.showMessageDialog(this, "Enter a number greater than 0!", title, JOptionPane.ERROR_MESSAGE);
                complete = false;
                out = -1;
            }//end if
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "You must enter a number!", title, JOptionPane.ERROR_MESSAGE);
            complete = false;
            out = -1;
        }//end tryCatch
        return out;
    }//end checkTextField

    @Override
    public void run() {
        if (ref != null && parent == null) {                                    //If called by the Base, use the input from this form to construct the next line placed by the user
            store = ref.getCanvas().getGtiStorage();
            initComponents();
            this.setVisible(true);
        }//end if
        else if (ref == null && parent != null) {                               //If called by a LineEventDetailsForm, use the input from this form to describe the line to be placed by the event
            store = parent.gti;
            initComponents();
            this.setVisible(true);
        }//end else if
    }//end run

}//end CustomLineForm
