package SwingElements;

import graphvisualizer.GraphTuple;

import java.util.Objects;

/**
 * Form containing options for debug features.
 */
public class DebugMenuForm extends javax.swing.JFrame implements Runnable {

    private Base ref;                                                                   //Base object, used for reference

    /**
     * Creates new form DebugMenuForm
     */
    DebugMenuForm(Base in) {
        ref = in;
        initComponents();
        DebugToggleCheckBox.setSelected(Canvas.DEBUG);
        GridLinesCheckBox.setSelected(Canvas.DEBUG_GRID_LINES);
        CenterLinesCheckBox.setSelected(Canvas.DEBUG_CENTER_LINES);
        MouseCoordinatesCheckBox.setSelected(Canvas.DEBUG_MOUSE_COORDINATES);
        BoundingRectangleCheckBox.setSelected(Canvas.DEBUG_BOUNDING_RECTANGLE);
        BoundingRectangleWidthTextField.setText(Integer.toString(Canvas.BOUNDING_RECTANGLE_WIDTH));
        BoundingRectangleHeightTextField.setText(Integer.toString(Canvas.BOUNDING_RECTANGLE_HEIGHT));

    }//end constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JComboBox jComboBox1 = new javax.swing.JComboBox();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        GridLinesCheckBox = new javax.swing.JCheckBox();
        MouseCoordinatesCheckBox = new javax.swing.JCheckBox();
        javax.swing.JLabel boundingRectangleWidthLabel = new javax.swing.JLabel();
        BoundingRectangleWidthTextField = new javax.swing.JTextField();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        CenterLinesCheckBox = new javax.swing.JCheckBox();
        BoundingRectangleCheckBox = new javax.swing.JCheckBox();
        javax.swing.JLabel boundingRectangleHeightLabel = new javax.swing.JLabel();
        BoundingRectangleHeightTextField = new javax.swing.JTextField();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        javax.swing.JLabel debugMenuLabel = new javax.swing.JLabel();
        DebugToggleCheckBox = new javax.swing.JCheckBox();
        javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        javax.swing.JButton applyButton = new javax.swing.JButton();
        javax.swing.JPanel jPanel6 = new javax.swing.JPanel();
        javax.swing.JLabel depthBasedColorIntervalLabel = new javax.swing.JLabel();
        DepthBasedColorIntervalComboBox = new javax.swing.JComboBox();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBackground(new java.awt.Color(255, 153, 0));

        jPanel1.setMaximumSize(new java.awt.Dimension(170, 100));
        jPanel1.setMinimumSize(new java.awt.Dimension(170, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(170, 100));

        GridLinesCheckBox.setText("Grid Lines");

        MouseCoordinatesCheckBox.setText("Mouse Coordinates");

        boundingRectangleWidthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boundingRectangleWidthLabel.setText("Bounding Rectangle Width");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(GridLinesCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MouseCoordinatesCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(BoundingRectangleWidthTextField))
                    .addComponent(boundingRectangleWidthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(GridLinesCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MouseCoordinatesCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boundingRectangleWidthLabel)
                .addGap(7, 7, 7)
                .addComponent(BoundingRectangleWidthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel2.setMaximumSize(new java.awt.Dimension(170, 100));
        jPanel2.setMinimumSize(new java.awt.Dimension(170, 100));

        CenterLinesCheckBox.setText("Center Lines");

        BoundingRectangleCheckBox.setText("Bounding Rectangle");

        boundingRectangleHeightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boundingRectangleHeightLabel.setText("Bounding Rectangle Height");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CenterLinesCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BoundingRectangleCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(BoundingRectangleHeightTextField))
                    .addComponent(boundingRectangleHeightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(CenterLinesCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BoundingRectangleCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boundingRectangleHeightLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(BoundingRectangleHeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        debugMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        debugMenuLabel.setText("Debug Menu");
        debugMenuLabel.setMaximumSize(new java.awt.Dimension(85, 23));
        debugMenuLabel.setMinimumSize(new java.awt.Dimension(85, 23));
        debugMenuLabel.setPreferredSize(new java.awt.Dimension(85, 23));

        DebugToggleCheckBox.setText(" Debug On?");
        DebugToggleCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DebugToggleCheckBox.setMaximumSize(new java.awt.Dimension(85, 23));
        DebugToggleCheckBox.setMinimumSize(new java.awt.Dimension(85, 23));
        DebugToggleCheckBox.setPreferredSize(new java.awt.Dimension(85, 23));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DebugToggleCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(debugMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(132, 132, 132))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(debugMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(DebugToggleCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setPreferredSize(new java.awt.Dimension(220, 23));

        applyButton.setText("Apply");
        applyButton.setMaximumSize(new java.awt.Dimension(60, 23));
        applyButton.setMinimumSize(new java.awt.Dimension(60, 23));
        applyButton.setPreferredSize(new java.awt.Dimension(60, 23));
        applyButton.addActionListener(evt -> ApplyButtonActionPerformed());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(applyButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        depthBasedColorIntervalLabel.setText("Depth-Based Coloring Interval");

        DepthBasedColorIntervalComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "3", "5", "15", "17", "51", "85", "255" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(depthBasedColorIntervalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DepthBasedColorIntervalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depthBasedColorIntervalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepthBasedColorIntervalComboBox))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Action handler for the apply button. Checks the form, then updates any
     * debug features according to what's on the form.
     */
    private void ApplyButtonActionPerformed() {//GEN-FIRST:event_ApplyButtonActionPerformed
        Canvas.DEBUG = DebugToggleCheckBox.isSelected();
        Canvas.DEBUG_GRID_LINES = GridLinesCheckBox.isSelected();
        Canvas.DEBUG_CENTER_LINES = CenterLinesCheckBox.isSelected();
        Canvas.DEBUG_MOUSE_COORDINATES = MouseCoordinatesCheckBox.isSelected();
        Canvas.DEBUG_BOUNDING_RECTANGLE = BoundingRectangleCheckBox.isSelected();
        String widthText = BoundingRectangleWidthTextField.getText();
        String heightText = BoundingRectangleHeightTextField.getText();
        Canvas.BOUNDING_RECTANGLE_WIDTH = isValidInteger(widthText) ? Integer.parseInt(widthText) : Canvas.BOUNDING_RECTANGLE_WIDTH;
        Canvas.BOUNDING_RECTANGLE_HEIGHT = isValidInteger(heightText) ? Integer.parseInt(heightText) : Canvas.BOUNDING_RECTANGLE_HEIGHT;
        GraphTuple.setDepthBasedColorInterval(Integer.parseInt((String) Objects.requireNonNull(DepthBasedColorIntervalComboBox.getSelectedItem())));
        this.dispose();
    }//GEN-LAST:event_ApplyButtonActionPerformed

    @Override
    public void run() {
        if (ref != null) {
            setVisible(true);
        }//end if
    }//end run
    private javax.swing.JCheckBox BoundingRectangleCheckBox;
    private javax.swing.JTextField BoundingRectangleHeightTextField;
    private javax.swing.JTextField BoundingRectangleWidthTextField;
    private javax.swing.JCheckBox CenterLinesCheckBox;
    private javax.swing.JCheckBox DebugToggleCheckBox;
    private javax.swing.JComboBox DepthBasedColorIntervalComboBox;
    private javax.swing.JCheckBox GridLinesCheckBox;
    private javax.swing.JCheckBox MouseCoordinatesCheckBox;
    // End of variables declaration//GEN-END:variables

    /**
     * Checks a String to ensure that it is an integer with a value greater than
     * zero.
     *
     * @param str The String to check
     * @return True if the String is a valid integer, false if not
     */
    private boolean isValidInteger(String str) {
        boolean out = false;
        try {
            int test = Integer.parseInt(str);
            out = test > 0;
        } catch (Exception ignored) {

        }//end try catch
        return out;
    }//end isValidInteger

}//end DebugMenuForm class
