package SwingElements;

import EventScheduler.Events.Event;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.util.Objects;

/**
 * Form used to input the details for the creation/editing of most {@link Event}
 * objects.
 */
public class EventDetailsInputForm extends javax.swing.JFrame implements Runnable {

    private SchedulerForm ref;                                                  //The SchedulerForm that generated the EventDetailsInputForm
    int stepCount;                                                       //The step count at which to execute the event in question
    String eventName;                                                    //The name of the event in question
    public boolean repeat;                                                      //Determines if the event is a repeat event or a single event
    private Event temp;                                                         //The event to be created/edited

    /**
     * Constructor. Used when an event is being created.
     *
     * @param in The {@link SchedulerForm} generating the
     * {@link EventDetailsInputForm}
     */
    EventDetailsInputForm(SchedulerForm in) {
        ref = in;
        initComponents();
        this.setTitle("Event Input Form");
    }//end constructor

    /**
     * Constructor. Used when an event is being edited.
     *
     * @param in The {@link SchedulerForm} generating the
     * {@link EventDetailsInputForm}
     * @param e The{@link Event} to be edited
     */
    EventDetailsInputForm(SchedulerForm in, Event e) {
        ref = in;
        temp = e;
        stepCount = e.getStepTarget();
        eventName = e.getEventName();
        repeat = e.getRepeat();
        initComponents();
        TriggerStepTextField.setText(String.valueOf(stepCount));
        EventNameTextField.setText(eventName);
        if (repeat) {
            RepeatEventComboBox.setSelectedIndex(0);
        }//end if
        else {
            RepeatEventComboBox.setSelectedIndex(1);
        }//end else
    }//end constructor

    /**
     * Checks a given {@link JTextField} to ensure that the input is numerical
     * and greater than 0.
     *
     * @param field The {@link JTextField} to be checked.
     * @return The final integer value after checking is performed
     */
    private int checkTextField(JTextField field) {
        int out;
        try {
            out = Integer.parseInt(field.getText());
            if (out <= 0) {
                JOptionPane.showMessageDialog(this, "Enter a number greater than 0!", "Trigger Step", JOptionPane.ERROR_MESSAGE);
                out = -1;
            }//end if
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "You must enter a number!", "Trigger Step", JOptionPane.ERROR_MESSAGE);
            out = -1;
        }//end tryCatch
        return out;
    }//end checkTextField

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel eventNameLabel = new javax.swing.JLabel();
        EventNameTextField = new javax.swing.JTextField();
        javax.swing.JLabel triggerStepLabel = new javax.swing.JLabel();
        TriggerStepTextField = new javax.swing.JTextField();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel repeatEventLabel = new javax.swing.JLabel();
        RepeatEventComboBox = new javax.swing.JComboBox();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        javax.swing.JButton createEventButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        eventNameLabel.setText("Event Name: ");

        EventNameTextField.setMaximumSize(new java.awt.Dimension(100, 20));
        EventNameTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        EventNameTextField.setPreferredSize(new java.awt.Dimension(100, 20));

        triggerStepLabel.setText("Trigger Step: ");

        TriggerStepTextField.setMaximumSize(new java.awt.Dimension(100, 23));
        TriggerStepTextField.setMinimumSize(new java.awt.Dimension(100, 23));
        TriggerStepTextField.setPreferredSize(new java.awt.Dimension(100, 23));

        repeatEventLabel.setText("Repeat Event? ");
        repeatEventLabel.setMaximumSize(new java.awt.Dimension(74, 23));
        repeatEventLabel.setMinimumSize(new java.awt.Dimension(74, 23));
        repeatEventLabel.setPreferredSize(new java.awt.Dimension(74, 23));

        RepeatEventComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No" }));
        RepeatEventComboBox.setMaximumSize(new java.awt.Dimension(50, 23));
        RepeatEventComboBox.setMinimumSize(new java.awt.Dimension(50, 23));
        RepeatEventComboBox.setPreferredSize(new java.awt.Dimension(50, 23));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(repeatEventLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RepeatEventComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(repeatEventLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(RepeatEventComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        createEventButton.setText("Create Event");
        createEventButton.addActionListener(this::CreateEventButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eventNameLabel)
                        .addGap(0, 0, 0)
                        .addComponent(EventNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(triggerStepLabel)
                        .addGap(0, 0, 0)
                        .addComponent(TriggerStepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(createEventButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventNameLabel)
                    .addComponent(EventNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(triggerStepLabel)
                    .addComponent(TriggerStepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createEventButton)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Action method for the create event button. Either creates a new event, or
     * updates the event to be edited.
     */
    private void CreateEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateEventButtonActionPerformed
        stepCount = checkTextField(TriggerStepTextField);
        eventName = EventNameTextField.getText();
        repeat = Objects.equals(RepeatEventComboBox.getSelectedItem(), "Yes");
        if (stepCount != -1) {
            if (temp == null) {
                ref.generateEvent();
            }//end if
            else {
                temp.setStepTarget(stepCount);
                temp.setEventName(eventName);
                temp.setRepeat(repeat);
                ref.updateRepeatEventList();
                ref.updateSingleEventList();
            }//end else
            this.dispose();
        }//end if
    }//GEN-LAST:event_CreateEventButtonActionPerformed

    private javax.swing.JTextField EventNameTextField;
    private javax.swing.JComboBox RepeatEventComboBox;
    private javax.swing.JTextField TriggerStepTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        if (ref != null) {
            setVisible(true);
        }//end if
    }//end run
}//end EventDetailsInputForm class
