package SwingElements;

import EventScheduler.Events.SavePictureEvent;
import java.io.File;
import java.util.Objects;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 * A form used to set up a {@link SavePictureEvent}.
 */
public class SavePictureEventDetailsForm extends javax.swing.JFrame implements Runnable {

    private SchedulerForm parent;
    int stepCount;
    String eventName;
    public boolean repeat;
    public String location = ".";
    private SavePictureEvent temp = null;

    /**
     * Creates new form SaveFieldEventDetailsForm.
     *
     * @param parentIn {@link Base} object used for reference
     */
    SavePictureEventDetailsForm(SchedulerForm parentIn) {
        parent = parentIn;
        initComponents();
    }//end constructor

    /**
     * Creates new form to edit given {@link SavePictureEvent}.
     *
     * @param parentIn {@link Base} object used for reference
     * @param eventIn The {@link SavePictureEvent} to be edited
     */
    SavePictureEventDetailsForm(SchedulerForm parentIn, SavePictureEvent eventIn) {
        parent = parentIn;
        temp = eventIn;

        initComponents();

        stepCount = temp.getStepTarget();
        eventName = temp.getEventName();
        repeat = temp.getRepeat();
        location = temp.getPictureLocation();
        TriggerStepTextField.setText(Integer.toString(stepCount));
        EventNameTextField.setText(eventName);
        FileLocationTextField.setText(location);
        if (repeat) {
            RepeatEventComboBox.setSelectedIndex(0);
        }//end if
        else {
            RepeatEventComboBox.setSelectedIndex(1);
        }//end else
    }//end constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel eventNameLabel = new javax.swing.JLabel();
        javax.swing.JLabel triggerStepLabel = new javax.swing.JLabel();
        EventNameTextField = new javax.swing.JTextField();
        TriggerStepTextField = new javax.swing.JTextField();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel repeatEventLabel = new javax.swing.JLabel();
        RepeatEventComboBox = new javax.swing.JComboBox();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        javax.swing.JButton createEventButton = new javax.swing.JButton();
        FileLocationTextField = new javax.swing.JTextField();
        javax.swing.JButton fileLocationBrowseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        eventNameLabel.setText("Event Name: ");

        triggerStepLabel.setText("Trigger Step: ");

        EventNameTextField.setMaximumSize(new java.awt.Dimension(100, 20));
        EventNameTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        EventNameTextField.setPreferredSize(new java.awt.Dimension(100, 20));

        TriggerStepTextField.setMaximumSize(new java.awt.Dimension(100, 23));
        TriggerStepTextField.setMinimumSize(new java.awt.Dimension(100, 23));
        TriggerStepTextField.setPreferredSize(new java.awt.Dimension(100, 23));

        repeatEventLabel.setText("Repeat Event? ");
        repeatEventLabel.setMaximumSize(new java.awt.Dimension(74, 23));
        repeatEventLabel.setMinimumSize(new java.awt.Dimension(74, 23));
        repeatEventLabel.setPreferredSize(new java.awt.Dimension(74, 23));

        RepeatEventComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No" }));
        RepeatEventComboBox.setMaximumSize(new java.awt.Dimension(50, 23));
        RepeatEventComboBox.setMinimumSize(new java.awt.Dimension(50, 23));
        RepeatEventComboBox.setPreferredSize(new java.awt.Dimension(50, 23));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(repeatEventLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RepeatEventComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(repeatEventLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(RepeatEventComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        createEventButton.setText("Create Event");
        createEventButton.addActionListener(this::CreateEventButtonActionPerformed);

        FileLocationTextField.setText(new File("").getAbsolutePath()
        );

        fileLocationBrowseButton.setText("Browse");
        fileLocationBrowseButton.addActionListener(this::FileLocationBrowseButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eventNameLabel)
                                .addGap(0, 0, 0)
                                .addComponent(EventNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(triggerStepLabel)
                                .addGap(0, 0, 0)
                                .addComponent(TriggerStepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(createEventButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FileLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileLocationBrowseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventNameLabel)
                    .addComponent(EventNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(triggerStepLabel)
                    .addComponent(TriggerStepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FileLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileLocationBrowseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(createEventButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Action handler for the create event button.
     */
    private void CreateEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateEventButtonActionPerformed
        stepCount = checkTextField(TriggerStepTextField);
        eventName = EventNameTextField.getText();
        repeat = Objects.equals(RepeatEventComboBox.getSelectedItem(), "Yes");
        if (stepCount != -1) {
            if (temp == null) {
                parent.generateEvent();
            }//end if
            else {
                temp.setStepTarget(stepCount);
                temp.setEventName(eventName);
                temp.setRepeat(repeat);
                temp.setPictureLocation(location);
                parent.updateRepeatEventList();
                parent.updateSingleEventList();
            }//end else
            this.dispose();
        }//end if
    }//GEN-LAST:event_CreateEventButtonActionPerformed

    /**
     * Action handler for the file location button.
     */
    private void FileLocationBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileLocationBrowseButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("."));
        chooser.setDialogTitle("Choose folder to save image in");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            location = chooser.getSelectedFile().getAbsolutePath();
            FileLocationTextField.setText(location);
        }//end if
    }//GEN-LAST:event_FileLocationBrowseButtonActionPerformed

    @Override
    public void run() {
        if (parent != null) {
            setVisible(true);
        }//end if
    }//end run

    /**
     * Checks a given {@link JTextField} to ensure that the input is numerical
     * and greater than 0.
     *
     * @param field The {@link JTextField} to be checked.
     * @return The final integer value after checking is performed
     */
    private int checkTextField(JTextField field) {
        int out;
        try {
            out = Integer.parseInt(field.getText());
            if (out <= 0) {
                JOptionPane.showMessageDialog(this, "Enter a number greater than 0!", "Trigger Step", JOptionPane.ERROR_MESSAGE);
                out = -1;
            }//end if
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "You must enter a number!", "Trigger Step", JOptionPane.ERROR_MESSAGE);
            out = -1;
        }//end tryCatch
        return out;
    }//end checkTextField

    private javax.swing.JTextField EventNameTextField;
    private javax.swing.JTextField FileLocationTextField;
    private javax.swing.JComboBox RepeatEventComboBox;
    private javax.swing.JTextField TriggerStepTextField;
    // End of variables declaration//GEN-END:variables
}//end SavePictureEventDetailsForm class
