package graphvisualizer;


import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Redpox
 */
public class GridSelectionFrame extends javax.swing.JFrame {

    /**
     * Creates new form GridSelectionFrame
     */
    public GridSelectionFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NumberOfColumnsLabel = new javax.swing.JLabel();
        NumberOfRowsLabel = new javax.swing.JLabel();
        NumberOfColumnsTextField = new javax.swing.JTextField();
        NumberOfRowsTextField = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        TimeBetweenStepsLabel = new javax.swing.JLabel();
        StepTimeTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NumberOfColumnsLabel.setText("Number of Columns");

        NumberOfRowsLabel.setText("Number of Rows");

        NumberOfColumnsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberOfColumnsTextFieldActionPerformed(evt);
            }
        });

        NumberOfRowsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberOfRowsTextFieldActionPerformed(evt);
            }
        });

        SubmitButton.setText("Ok");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        TimeBetweenStepsLabel.setText("Time between steps");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NumberOfColumnsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(NumberOfRowsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NumberOfColumnsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NumberOfRowsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(SubmitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TimeBetweenStepsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StepTimeTextField))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumberOfColumnsLabel)
                    .addComponent(NumberOfRowsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumberOfColumnsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberOfRowsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TimeBetweenStepsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StepTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SubmitButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumberOfColumnsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberOfColumnsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberOfColumnsTextFieldActionPerformed

    private void NumberOfRowsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberOfRowsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberOfRowsTextFieldActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
       int c = checkTextField(NumberOfColumnsTextField);
       int r = checkTextField(NumberOfRowsTextField);
       int st = checkTextField(StepTimeTextField);
       if(c != -1 && r != -1){
           new Base(c,r,st).setVisible(true);
           this.dispose();
       }//end if
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private int checkTextField(JTextField field){
        int out;
        try{
            out = Integer.parseInt(field.getText());
            if(out <= 0){
                JOptionPane.showMessageDialog(this, "Enter a number greater than 0!", null, JOptionPane.ERROR_MESSAGE);
                out = -1;
            }//end if
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "You must enter a number!", null, JOptionPane.ERROR_MESSAGE);
            out = -1;
        }//end tryCatch
        return out;
    }//end checkTextField
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NumberOfColumnsLabel;
    private javax.swing.JTextField NumberOfColumnsTextField;
    private javax.swing.JLabel NumberOfRowsLabel;
    private javax.swing.JTextField NumberOfRowsTextField;
    private javax.swing.JTextField StepTimeTextField;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel TimeBetweenStepsLabel;
    // End of variables declaration//GEN-END:variables
}
